# Generated by Django 5.2 on 2025-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projectimg/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('skills', models.ManyToManyField(related_name='ptojects', to='home.skill')),
            ],
        ),
    ]
