# Generated by Django 5.2 on 2025-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_skill_icon_homeproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='githubLink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeproject',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='home.skill'),
        ),
    ]
