# Generated by Django 5.2 on 2025-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homeproject_githublink_alter_homeproject_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfIntroTitle', models.CharField(max_length=50)),
                ('selfIntro', models.CharField(max_length=150)),
                ('EducationTitle', models.CharField(max_length=50)),
                ('Education', models.CharField(max_length=150)),
                ('LanguagesTitle', models.CharField(max_length=50)),
                ('Languages', models.CharField(max_length=150)),
            ],
        ),
    ]
