# Generated by Django 5.2 on 2025-06-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='Education',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='EducationTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='intro',
            name='Languages',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='LanguagesTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='intro',
            name='selfIntro',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='intro',
            name='selfIntroTitle',
            field=models.CharField(max_length=100),
        ),
    ]
