# Generated by Django 5.2 on 2025-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_intro_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
