# Generated by Django 5.2 on 2025-07-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homeproject_show_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproject',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intro',
            name='profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
