# Generated by Django 5.2 on 2025-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homeproject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproject',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
