# Generated by Django 5.2 on 2025-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homeproject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproject',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
